apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-task
spec:
  description: >-
    This task performs cleanup operations such as removing temporary files or images.
  steps:
    - name: cleanup
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/source/tmp/*
        echo "Cleanup done."
